sonar.projectKey=qr-farm
sonar.projectName=QR-Farm
sonar.sourceEncoding=UTF-8
sonar.sources=backend/src,frontend/src
sonar.tests=backend/tests
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.cobertura.reportPaths=frontend/coverage-frontend/cobertura-frontend.xml
sonar.language=py,js
sonar.python.version=3.14.0
