sonar.projectKey=qr-farm
sonar.projectName=QR-Farm
sonar.sourceEncoding=UTF-8
sonar.sources=backend/src,interfaz/src
sonar.tests=backend/tests
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.language=py,js